// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.45.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import "bridge_definitions.dart";
import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'gened_api_2.io.dart' if (dart.library.html) 'gened_api_2.web.dart';
import 'package:meta/meta.dart';

class Api_2Impl implements Api_2 {
  final Api_2Platform _platform;
  factory Api_2Impl(ExternalLibrary dylib) =>
      Api_2Impl.raw(Api_2Platform(dylib));

  /// Only valid on web/WASM platforms.
  factory Api_2Impl.wasm(FutureOr<WasmModule> module) =>
      Api_2Impl(module as ExternalLibrary);
  Api_2Impl.raw(this._platform);
  Future<void> testPrint2({required String log, dynamic hint}) =>
      _platform.executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner
            .wire_test_print_2(port_, _platform.api2wire_String(log)),
        parseSuccessData: _wire2api_unit,
        constMeta: kTestPrint2ConstMeta,
        argValues: [log],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kTestPrint2ConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "test_print_2",
        argNames: ["log"],
      );
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: wire2api

void _wire2api_unit(dynamic raw) {
  return;
}
